server:
  port: 18080

spring:
  application:
    name: consumer

dubbo:
  application:
    service-discovery:
      migration: FORCE_APPLICATION
    #禁用QOS同一台机器可能会有端口冲突现象
    qos:
      enable: false
      accept:
        foreign:
          ip: false
  registry:
    address: nacos://127.0.0.1:8848