server:
  port: 18080

dubbo:
  application:
    service-discovery:
      migration: INTERFACE_FIRST #FORCE_APPLICATION
    name: c-consumer
    #禁用QOS同一台机器可能会有端口冲突现象
    qosEnable: false
    qosAcceptForeignIp: false
  registry:
    address: nacos://127.0.0.1:8848
    group: dubbo
    useAsConfigCenter: false
    useAsMetadataCenter: false